# Travis CI Configuration

language: node_js
node_js:
  - "10"
  - "11"
  - "12"
install:
  - npm install
  - npm install coveralls
before_script:
  - gulp build
script:
  - npm run coverage
after_success:
  - cat coverage/lcov.info | coveralls
